// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_adventure_begins = "CgkI2eOjhJgZEAIQAA"; // <GPGSID>
        public const string achievement_brutal = "CgkI2eOjhJgZEAIQBw"; // <GPGSID>
        public const string achievement_defeat_demon_lord = "CgkI2eOjhJgZEAIQAw"; // <GPGSID>
        public const string achievement_wizards_trainee = "CgkI2eOjhJgZEAIQCA"; // <GPGSID>
        public const string achievement_impenetrable_arapace = "CgkI2eOjhJgZEAIQBQ"; // <GPGSID>
        public const string achievement_fearsome_weapon = "CgkI2eOjhJgZEAIQBg"; // <GPGSID>
        public const string achievement_fabulous_marksman = "CgkI2eOjhJgZEAIQBA"; // <GPGSID>
        public const string leaderboard_postponed_for_retirement = "CgkI2eOjhJgZEAIQCQ"; // <GPGSID>
        public const string achievement_defeat_polar_ursa = "CgkI2eOjhJgZEAIQAg"; // <GPGSID>
        public const string achievement_defeat_bubarossa = "CgkI2eOjhJgZEAIQAQ"; // <GPGSID>

}

